### ISSUE TITLE
[Spanish] UI terms

### ISSUE THREAD

**Issue by remibetin** [w3c/wai-translations#103]
Needs update

UI terms file: https://github.com/w3c/wai-website-data/blob/master/translations.yml

English terms without `es` translations:

```yaml
- en: 'Next'  # used for navigation to the next page in a multi-page resource; for example, just above w3.org/WAI/people-use-web/user-stories/#helpimprove

- en: 'Previous'  # used for navigation to the previous page in a multi-page resource; for example, just above w3.org/WAI/people-use-web/user-stories/#helpimprove

- en: 'in'  # for "[resource sub-page title] in [parent resource title]" such as [Stories of Web Users] in [How People with Disabilities Use the Web] at w3.org/WAI/people-use-web/user-stories/

```
