### ISSUE TITLE
[Brazilian Portuguese] UI terms

### ISSUE THREAD

**Issue by remibetin** [w3c/wai-translations#88]
Needs update

UI terms file: https://github.com/w3c/wai-website-data/blob/master/translations.yml

- [x] Add `pt-BR` translations for the following english terms:

```yaml
- en: 'in'  # for "[resource sub-page title] in [parent resource title]" such as [Stories of Web Users] in [How People with Disabilities Use the Web] at w3.org/WAI/people-use-web/user-stories/

- en: 'Expand All Sections'  # for expand-collapse toggle buttons such as under the Page Contents at w3.org/WAI/people-use-web/user-stories/

- en: 'Collapse All Sections'  # for expand-collapse toggle buttons such as under the Page Contents at w3.org/WAI/people-use-web/user-stories/

- en: 'This video is available with more accessibility features:'   # Text under videos such as at w3.org/WAI/test-evaluate/#initial -- with the title of the video after this phrase

# The 3 next phrases are combined with a number to created "to footnote 1" and "back to footnote 1 in text" in https://www.w3.org/WAI/business-case/#fn:1

- en: 'to footnote'

- en: 'back to footnote'

- en: 'in text'

```

- [x] Check what needs update
