### ISSUE TITLE
[German] UI terms

### ISSUE THREAD

**Issue by remibetin** [w3c/wai-translations#90]
Needs update

UI terms file: https://github.com/w3c/wai-website-data/blob/master/translations.yml

- [x] Add `de` translations for the following English terms:

```yaml
- en: 'Hide'   # for show/hide toggle, for example, on the WAI home page: “Hide Section”

- en: 'This video is available with more accessibility features:'   # Text under videos such as at w3.org/WAI/test-evaluate/#initial -- with the title of the video after this phrase

# The 3 next phrases are combined with a number to created "to footnote 1" and "back to footnote 1 in text" in https://www.w3.org/WAI/business-case/#fn:1

- en: 'to footnote'

- en: 'back to footnote'

- en: 'in text'

- en: 'Acknowledgements'
 
- en: 'Standards/Guidelines' # Precedes list of translations of standards and guidelines in this language, in https://www.w3.org/WAI/translations/

```
